inputs:
  registry:
    description: 'Docker registry'
    default: 'ghcr.io'
    type: string
  image-name:
    description: 'Docker image name'
    default: '${{ github.repository }}'
    type: string
  username:
    description: 'Username for Docker registry'
    default: '${{ github.actor }}'
    type: string
  password:
    description: 'Password for Docker registry'
    default: '${{ github.token }}'
    type: string
  platforms:
    description: 'Platforms to build for'
    default: 'linux/amd64,linux/arm64'
    type: string

outputs:
  digest:
    description: "Digest of built image"
    value: ${{ steps.set-outputs.outputs.digest }}
  image-name:
    description: "Metadata of built image"
    value: ${{ steps.set-outputs.outputs.image-name }}

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8 # tag=v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # tag=v2

    - name: Log in to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # tag=v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a # tag=v4
      with:
        images: ${{ inputs.registry }}/${{ inputs.image-name }}
        tags: |
          type=schedule,pattern=${{ github.ref_name }}
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr

    - name: Build and push Docker image
      uses: docker/build-push-action@1cb9d22b932e4832bb29793b7777ec860fc1cde0 # tag=v3
      with:
        platforms: ${{ inputs.platforms }}
        push: ${{ github.event_name != 'pull_request' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
      id: build-push

    - name: Set output
      run: |
        echo "::set-output name=digest::$(echo "${metadata}" | jq -r '.["containerimage.digest"]')"
        echo "::set-output name=image-name::$(echo "${metadata}" | jq -r '.["image.name"]')"
      shell: bash
      env:
        metadata: ${{ steps.build-push.outputs.metadata }}
      id: set-outputs
