inputs:
  registry:
    description: 'Docker registry'
    default: 'ghcr.io'
    type: string
  image-name:
    description: 'Docker image name'
    default: '${{ github.repository }}'
    type: string
  username:
    description: 'Username for Docker registry'
    default: '${{ github.actor }}'
    type: string
  password:
    description: 'Password for Docker registry'
    default: '${{ github.token }}'
    type: string
  platforms:
    description: 'Platforms to build for'
    default: 'linux/amd64,linux/arm64'
    type: string

outputs:
  digest:
    description: "Digest of built image"
    value: ${{ steps.set-outputs.outputs.digest }}
  image-name:
    description: "Metadata of built image"
    value: ${{ steps.set-outputs.outputs.image-name }}

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

    - name: Log in to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@318604b99e75e41977312d83839a89be02ca4893 # v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.image-name }}
        tags: |
          type=schedule,pattern=${{ github.ref_name }}
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr

    - name: Build and push Docker image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
      with:
        platforms: ${{ inputs.platforms }}
        push: ${{ github.event_name != 'pull_request' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
      id: build-push

    - name: Set output
      run: |
        echo "::set-output name=digest::$(echo "${metadata}" | jq -r '.["containerimage.digest"]')"
        echo "::set-output name=image-name::$(echo "${metadata}" | jq -r '.["image.name"]')"
      shell: bash
      env:
        metadata: ${{ steps.build-push.outputs.metadata }}
      id: set-outputs
