inputs:
  registry:
    description: 'Docker registry'
    default: 'ghcr.io'
    type: string
  image-name:
    description: 'Docker image name'
    default: '${{ github.repository }}'
    type: string
  username:
    description: 'Username for Docker registry'
    default: '${{ github.actor }}'
    type: string
  password:
    description: 'Password for Docker registry'
    default: '${{ github.token }}'
    type: string
  platforms:
    description: 'Platforms to build for'
    default: 'linux/amd64,linux/arm64'
    type: string

outputs:
  digest:
    description: "Digest of built image"
    value: ${{ steps.set-outputs.outputs.digest }}
  image-name:
    description: "Metadata of built image"
    value: ${{ steps.set-outputs.outputs.image-name }}

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # tag=v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325 # tag=v2

    - name: Log in to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96 # v4
      with:
        images: ${{ inputs.registry }}/${{ inputs.image-name }}
        tags: |
          type=schedule,pattern=${{ github.ref_name }}
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr

    - name: Build and push Docker image
      uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5 # tag=v3
      with:
        platforms: ${{ inputs.platforms }}
        push: ${{ github.event_name != 'pull_request' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
      id: build-push

    - name: Set output
      run: |
        echo "::set-output name=digest::$(echo "${metadata}" | jq -r '.["containerimage.digest"]')"
        echo "::set-output name=image-name::$(echo "${metadata}" | jq -r '.["image.name"]')"
      shell: bash
      env:
        metadata: ${{ steps.build-push.outputs.metadata }}
      id: set-outputs
