on:
  push:
    branches:
      - main

name: Ansible Bastion

jobs:
  ansible-bastion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Configure Ansible bastion host
        uses: reitermarkus/.github/actions/ansible-bastion@f536771589b3228b7b9296b7c3715a5717f28c38 # main
        with:
          host: ${{ secrets.ANSIBLE_BASTION_HOST }}
          key: ${{ secrets.ANSIBLE_BASTION_KEY }}

      - name: Run Ansible
        run: |
          ansible opnsense -i inventory.yml -a 'hostname -f'

