on:
  push:
    branches:
      - main

name: Ansible Bastion

jobs:
  ansible-bastion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Configure Ansible bastion host
        uses: reitermarkus/.github/actions/ansible-bastion@b07d75e134de3b8deca2cead5535fb9a8977137b # main
        with:
          host: ${{ secrets.ANSIBLE_BASTION_HOST }}
          key: ${{ secrets.ANSIBLE_BASTION_KEY }}

      - name: Run Ansible
        run: |
          ansible opnsense -i inventory.yml -a 'hostname -f'

