on: [pull_request, push]

name: CI

jobs:
  ci:
    uses: reitermarkus/.github/.github/workflows/docker-build-push.yml@6ef3c6e3f481873ede49fca680cc9f4482991050 # main
    with:
      image-name: ${{ github.repository_owner }}/github
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@eaf12548c13069dcc28bb75c4ee4610cdbe400c5 # v44.2.6
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.GH_TOKEN }}
        env:
          LOG_LEVEL: 'debug'

      - name: Validate Renovate config
        uses: rinchsan/renovate-config-validator@8cf44ae5646f111f838a03ac7ebd4e1c1f9be983 # v0.2.1
        with:
          pattern: '*.json'
